<?php

namespace App\Services\Banks\Drivers;

use App\Data\Bank\AccountData;
use App\Data\Bank\ContactData;
use App\Data\Bank\CredentialPromptsData;
use App\Data\Bank\LoginResultData;
use App\Data\Bank\TransactionData;
use App\Data\Bank\TransferQuoteData;
use App\Data\Bank\TransferReceiptData;
use App\Data\Bank\TransferRequestData;
use App\Data\Bank\VoucherData;
use App\Data\Bank\VoucherDenominationData;
use App\Data\Bank\VoucherProviderData;
use App\Data\Bank\VoucherPurchaseRequestData;
use App\Data\Bank\VoucherQuoteData;
use App\Exceptions\BankApiException;
use App\Services\Banks\AbstractBankDriver;
use App\Services\Banks\Contracts\SellsVouchers;
use App\Services\Banks\Support\LibyanIban;
use Carbon\Carbon;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Str;
use Spatie\LaravelData\DataCollection;

/**
 * Driver for North Africa Bank's "nabmobile" API.
 *
 * Logins use phone number + password + a device key generated by the client.
 * The API issues short-lived access tokens without a refresh token, so the
 * driver re-logs in with the stored credentials when the token expires.
 * Each login is bound to a single account, described by the JWT claims.
 */
class NabDriver extends AbstractBankDriver implements SellsVouchers
{
    private const CURRENCY = 'LYD';

    public function credentialPrompts(): CredentialPromptsData
    {
        return new CredentialPromptsData(
            identifier_label: 'Phone number',
            secret_label: 'Password',
            identifier_hint: 'e.g. 92xxxxxxx',
        );
    }

    public function login(string $identifier, string $secret): LoginResultData
    {
        $deviceKey = $this->session->device_id ?: Str::lower(Str::random(32));

        $this->session->update([
            'customer_id' => $identifier,
            'device_id' => $deviceKey,
            'credentials' => ['phone' => $identifier, 'password' => $secret],
        ]);

        return LoginResultData::authenticated($this->authenticate());
    }

    public function verifyOtp(string $code): LoginResultData
    {
        throw new BankApiException("{$this->bank->displayName()} logins do not use an OTP.");
    }

    protected function reauthenticate(): bool
    {
        if ($this->credential('password') === null) {
            return false;
        }

        $this->authenticate();

        return true;
    }

    public function accounts(): DataCollection
    {
        $balance = $this->throwIfFailed($this->request()->get('/api/balance'), 'errorMessage')->json('balance');

        return AccountData::collect([[
            'number' => $this->meta('accountNumber'),
            'available_balance' => (string) $balance,
            'available_balance_formatted' => $this->formatAmount($balance, self::CURRENCY),
            'currency' => self::CURRENCY,
            'description' => $this->meta('branchName'),
            'iban' => $this->meta('iban'),
        ]], DataCollection::class);
    }

    public function transactions(string $accountNumber): DataCollection
    {
        $transactions = array_map(fn (array $transaction) => [
            'reference' => $transaction['trnRef'],
            'type' => $transaction['transactionType'] === 'C' ? TransactionData::TYPE_CREDIT : TransactionData::TYPE_DEBIT,
            'type_label' => $transaction['transactionType'] === 'C' ? 'Credit' : 'Debit',
            'date' => $transaction['transactionDt'],
            'amount' => (string) $transaction['amount'],
            'amount_formatted' => $this->formatAmount($transaction['amount'], self::CURRENCY),
            'currency' => self::CURRENCY,
            'code_description' => $transaction['trnCdDesc'] ?? '',
            'description' => $transaction['desc'] ?? null,
        ], $this->rawTransactions($accountNumber)['transactions'] ?? []);

        return TransactionData::collect($transactions, DataCollection::class);
    }

    public function rawTransactions(string $accountNumber): mixed
    {
        $days = (int) $this->bank->config('statement_days', 7);

        return $this->throwIfFailed($this->request()->get('/api/statement', [
            'fromDate' => now()->subDays($days)->toDateString(),
            'toDate' => now()->toDateString(),
        ]), 'errorMessage')->json();
    }

    public function contacts(): DataCollection
    {
        return ContactData::collect(array_map(fn (array $entry) => [
            'name' => $entry['creditorName'],
            'identification' => $entry['creditorIban'],
            'schema' => ContactData::SCHEMA_IBAN,
            'institution_code' => $entry['creditorInstitutionId'] ?? null,
            'institution_name' => $entry['creditorInstitution'] ?? null,
        ], $this->whitelist()), DataCollection::class);
    }

    public function initiateTransfer(TransferRequestData $request): TransferQuoteData
    {
        $iban = LibyanIban::normalize($request->iban);
        $creditor = $this->whitelistedCreditor($iban) ?? $this->whitelistCreditor($iban);

        $this->throwIfFailed($this->request()->get('/api/Otp/Request'), 'errorMessage');

        return new TransferQuoteData(
            amount_formatted: $this->formatAmount($request->amount, $request->currency),
            total_amount_formatted: $this->formatAmount($request->amount, $request->currency),
            currency: $request->currency,
            creditor_identification: $iban,
            requires_otp: true,
            description: $request->description,
            debtor_name: $this->meta('fullName'),
            creditor_name: $creditor['name'],
            meta: [
                'amount' => $request->amount,
                'bank' => LibyanIban::bankCode($iban),
            ],
        );
    }

    public function confirmTransfer(TransferQuoteData $quote, ?string $otp = null): TransferReceiptData
    {
        $response = $this->request()->post('/api/ips', [
            'amount' => (float) $quote->meta['amount'],
            'iBan' => $quote->creditor_identification,
            'bank' => $quote->meta['bank'],
            'description' => $quote->description ?: $quote->creditor_name,
            'transactionType' => 'P2P',
            'otp' => $otp,
            'internalMerchantReference' => null,
        ]);

        $this->throwIfFailed($response, 'errorMessage');

        return new TransferReceiptData(reference: $response->json('id'));
    }

    public function voucherProviders(): DataCollection
    {
        return VoucherProviderData::collect(array_map(fn (array $type) => [
            'id' => (string) $type['id'],
            'name' => $type['nameAr'],
        ], $this->voucherTypes()), DataCollection::class);
    }

    public function voucherDenominations(string $providerId): DataCollection
    {
        $type = collect($this->voucherTypes())->first(fn (array $type) => (string) $type['id'] === $providerId);

        return VoucherDenominationData::collect(array_map(fn (array $category) => [
            'id' => (string) $category['id'],
            'amount' => (string) $category['price'],
            'currency' => self::CURRENCY,
            'label' => $category['description'],
        ], $type['categories'] ?? []), DataCollection::class);
    }

    public function purchaseVoucher(VoucherPurchaseRequestData $request): VoucherQuoteData
    {
        $provider = $this->voucherProviders()->toCollection()->firstWhere('id', $request->provider_id);
        $denomination = $this->voucherDenominations($request->provider_id)->toCollection()->firstWhere('id', $request->denomination_id);

        if ($provider === null || $denomination === null) {
            throw new BankApiException('Unknown voucher provider or amount.');
        }

        return new VoucherQuoteData(
            account_number: $request->account_number,
            provider_id: $provider->id,
            provider_name: $provider->name,
            amount: $denomination->amount,
            amount_formatted: $this->formatAmount($denomination->amount, self::CURRENCY),
            currency: self::CURRENCY,
            requires_otp: false,
            meta: ['category_id' => (int) $denomination->id],
        );
    }

    public function confirmVoucherPurchase(VoucherQuoteData $quote, ?string $otp = null): VoucherData
    {
        $response = $this->throwIfFailed($this->request()->post('/api/vouchers', [
            'voucherCategoryId' => $quote->meta['category_id'],
        ]), 'errorMessage');

        return new VoucherData(
            provider_name: $response->json('description') ?? $quote->provider_name,
            amount: (string) ($response->json('price') ?? $quote->amount),
            currency: self::CURRENCY,
            code: (string) $response->json('voucherCode'),
            purchased_at: $response->json('boughtAt'),
        );
    }

    /** @return list<array<string, mixed>> */
    private function voucherTypes(): array
    {
        return $this->throwIfFailed($this->request()->get('/api/vouchers/types'), 'errorMessage')->json() ?? [];
    }

    /**
     * Log in with the stored credentials, persist the token and the account claims it carries.
     */
    private function authenticate(): ?string
    {
        $response = $this->http()->post('/api/identity/login', [
            'phoneNumber' => $this->credential('phone'),
            'password' => $this->credential('password'),
            'deviceKey' => $this->session->device_id,
        ]);

        $this->throwIfFailed($response, 'errorMessage');

        $token = $response->json('accessToken');

        if (! is_string($token) || $token === '') {
            throw new BankApiException("{$this->bank->displayName()} did not return an access token.", $response->status(), $response->json());
        }

        $claims = $this->jwtClaims($token);

        $this->session->update([
            'access_token' => $token,
            'access_token_expires_at' => Carbon::now()->addSeconds((int) ($response->json('expiresIn') ?? 1800)),
        ]);

        $this->rememberMeta([
            'accountNumber' => $claims['accountNumber'] ?? null,
            'iban' => $claims['iban'] ?? null,
            'fullName' => $claims['fullName'] ?? null,
            'branchName' => $claims['branchName'] ?? null,
        ]);

        return $claims['fullName'] ?? null;
    }

    /** @return list<array<string, mixed>> */
    private function whitelist(): array
    {
        return $this->throwIfFailed($this->request()->get('/api/ips/whitelist'), 'errorMessage')->json() ?? [];
    }

    /** @return array{name: string}|null */
    private function whitelistedCreditor(string $iban): ?array
    {
        foreach ($this->whitelist() as $entry) {
            if (LibyanIban::normalize($entry['creditorIban'] ?? '') === $iban) {
                return ['name' => $entry['creditorName']];
            }
        }

        return null;
    }

    /** @return array{name: string} */
    private function whitelistCreditor(string $iban): array
    {
        $verified = $this->throwIfFailed($this->request()->post('/api/ips/whitelist/verify', [
            'identification' => $iban,
            'schemaName' => 'iban',
            'type' => 'P',
        ]), 'errorMessage');

        $this->throwIfFailed($this->request()->post('/api/ips/whitelist/active', [
            'identification' => $iban,
        ]), 'errorMessage');

        return ['name' => $verified->json('creditorName') ?? $iban];
    }

    /** @return array<string, mixed> */
    private function jwtClaims(string $token): array
    {
        $payload = explode('.', $token)[1] ?? '';
        $decoded = base64_decode(strtr($payload, '-_', '+/'), true);

        return is_string($decoded) ? (json_decode($decoded, true) ?? []) : [];
    }

    private function request(): PendingRequest
    {
        return $this->authenticated();
    }
}
